# Generated by Django 5.2.1 on 2025-05-31 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listing_comment_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='creator',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='creator',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='creator',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='starting_bid',
        ),
        migrations.AddField(
            model_name='bid',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watched_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_listings_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
