# Generated by Django 5.2.1 on 2025-06-02 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_created_at_user_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='current',
            new_name='is_current',
        ),
    ]
